### ISSUE TITLE
Hyperlinks in descriptions not always distinguishable from regular text

### ISSUE THREAD

**Issue by Rayne** [aljawaid/KanboardCSS#10]
Hyperlinks embedded in descriptions are not always distinguishable from regular text. The foreground color is black and no background color is defined.

The CSS selector is too restrictive, e.g. it ignores hyperlinks that are not the first element inside a list item.

https://github.com/aljawaid/KanboardCSS/blob/359502bcf7f00671b9e8e2b126a3f5e604ce30b7/kanboardcss.css#L452-L457

I'm using the following snippet for unordered and ordered lists as workaround:

```css
.markdown ul li a, .markdown ol li a {
    color: white;
    background-color: grey;
    padding: 2px 4px;
    border-radius: 3px;
}

.markdown ul li a code {
    color: white;
}
```

I have added the `code` section because I'm sometimes embedding `<code>` segments in hyperlinks.

**Before**

![before](https://user-images.githubusercontent.com/1098733/68956429-576f7f80-07c8-11ea-80aa-fddfc7baa6d0.png)

**After**

![after](https://user-images.githubusercontent.com/1098733/68956438-5b030680-07c8-11ea-8346-5546da0eb9a2.png)
